#define the sonar parameters
horizontalFOV: 130.0
transformation: -0.087
verticalAperture: 20.0
horizontalTopic: "/rexrov/forward_sonar_horiz/raw_sonar"
verticalTopic: "/rexrov/forward_sonar_vert/raw_sonar"

#define which implmentation we want to match the features
method: cpp # options are cpp or python

#do we want to see the feature images from CFAR? turn on to publish
visFeatures: True

#define the matching paramters
uncertaintyMax: .97
patchSize: 6

#UUV sim
tcHorizontal: 20
gcHorizontal: 10
pfaHorizontal: .2
thresholdHorizontal: 145.
#define CFAR for the vertical sonar
tcVertical: 10
gcVertical: 10
pfaVertical: .1
thresholdVertical: 137.

#Holoocean
#tcHorizontal: 40
#gcHorizontal: 20
#pfaHorizontal: .1
#thresholdHorizontal: 85
#
#tcVertical: 40
#gcVertical: 20
#pfaVertical: .1
#thresholdVertical: 85