#define the sonar parameters
horizontalFOV: 130.0
transformation: 0.1
verticalAperture: 20.0
horizontalTopic: "/rexrov/forward_sonar_horiz/raw_sonar"
verticalTopic: "/rexrov/forward_sonar_vert/raw_sonar"

#define the matching paramters
uncertaintyMax: .97
patchSize: 6

#define CFAR for the horizontal sonar
tcHorizontal: 80
gcHorizontal: 80
pfaHorizontal: .2
thresholdHorizontal: 137.

#define CFAR for the vertical sonar
tcVertical: 10
gcVertical: 10
pfaVertical: .1
thresholdVertical: 137.